version: "3.6"
services:
  tomcat:
    build:
      context: ./docker
      args:
        - TZ=${TZ}
    tty: true
    environment:
      - TZ=${TZ}
    ports:
      - 18080:8080
    volumes:
      - ./tomcat:/usr/local/tomcat
